# ASSIGNMENT 3

# Question 1

In [1]:
import numpy as np
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2

In [5]:
import numpy as np
list1=[]
list2=[]
print("enter elements of 1st list\n")
i=0
while i<5:
    list1.append(int(input()))
    i=i+1
print("enter elements of 2nd list\n")
i=0
while (i<5):
    list2.append(int(input()))
    i=i+1
    
arr1=np.array(list1)
arr2=np.array(list2)

print("list1:",list1)
print("list2:",list2)
print("array 1:",arr1)
print("array 2:",arr2)

arr3=np.array(np.concatenate((arr1,arr2)))
print("concatenated array",arr3)

print("sorted array 1\n")
print(np.sort(arr1))

print("sorted array 2\n")
print(np.sort(arr2))

print("sorted concatenated array\n")
print(np.sort(arr3))


enter elements of 1st list

1
3
5
7
9
enter elements of 2nd list

2
4
6
8
10
list1: [1, 3, 5, 7, 9]
list2: [2, 4, 6, 8, 10]
array 1: [1 3 5 7 9]
array 2: [ 2  4  6  8 10]
concatenated array [ 1  3  5  7  9  2  4  6  8 10]
sorted array 1

[1 3 5 7 9]
sorted array 2

[ 2  4  6  8 10]
sorted concatenated array

[ 1  2  3  4  5  6  7  8  9 10]


# Question 3

In [7]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print ("array dimension:",arr.ndim)
print ("array size:",arr.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array dimension: 2
array size: 12


# Question 4

In [8]:
import numpy as np
arr1=np.array([1,2,3,4])
print("1D ARRAY:",arr1)
rearr=np.reshape(arr1,(-1,2))
print("reshaped 2D:",rearr)

1D ARRAY: [1 2 3 4]
reshaped 2D: [[1 2]
 [3 4]]


In [12]:
import numpy as np
x = np.array([2,3,6,7,9])
y = x[:, np.newaxis]
print(y)

[[2]
 [3]
 [6]
 [7]
 [9]]


# Question 5

In [11]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print("vertical stacking: \n",np.vstack((arr1,arr2)))
print("horizontal stacking: \n",np.hstack((arr1,arr2)))

vertical stacking: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stacking: 
 [[1 2 5 6]
 [3 4 7 8]]


# Question 6

In [14]:
a= np.array([1, 1, 2, 3, 4, 4, 5, 6])

np.unique(a)


array([1, 2, 3, 4, 5, 6])

In [15]:
np.count_nonzero(np.unique(a))

6